security:
    encoders:
        ChildConnect\CCSoftBundle\Entity\User: sha512

    role_hierarchy:
        ROLE_USER: ROLE_UNFILLED_USER 
        ROLE_ADMIN_ASSOC: ROLE_USER
        ROLE_ADMIN: [ROLE_USER, ROLE_ADMIN_ASSOC]
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN_ASSOC, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        main:
            id: fos_user.user_provider.username

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        login:
            pattern:  ^/appli/login$
            anonymous: true


        secured_area:
            pattern:  ^/
            anonymous: true
            provider:  main
            form_login:
                login_path: fos_user_security_login
                check_path: fos_user_security_check
                default_target_path: /enfant/modifiedAt/DESC/page-1/12/list
            logout:
                path:   fos_user_security_logout
                target: /login
                invalidate_session: false

        #unsecured_area:
            #pattern:  ^/page
            #anonymous: true
            #provider:  main

    access_control:
        - { path: ^/$, roles: IS_AUTHENTICATED_FULLY, requires_channel: http }
        - { path: ^/quiz, roles: IS_AUTHENTICATED_FULLY, requires_channel: http }
        - { path: ^/question, roles: IS_AUTHENTICATED_FULLY, requires_channel: http }
        - { path: ^/enfant, roles: IS_AUTHENTICATED_FULLY, requires_channel: http }
        - { path: ^/association, roles: IS_AUTHENTICATED_FULLY, requires_channel: http }
        - { path: ^/event, roles: IS_AUTHENTICATED_FULLY, requires_channel: http }
        - { path: ^/lieu, roles: IS_AUTHENTICATED_FULLY, requires_channel: http }
        - { path: ^/user, roles: IS_AUTHENTICATED_FULLY, requires_channel: http }
        - { path: ^/stats, roles: IS_AUTHENTICATED_FULLY, requires_channel: http }
        - { path: ^/ajax, roles: IS_AUTHENTICATED_FULLY, requires_channel: http }
        - { path: ^/_admin, roles: [ROLE_ASSOC, ROLE_ADMIN], requires_channel: http }
        - { path: ^/_console, roles: ROLE_SUPER_ADMIN, requires_channel: http }
        - { path: ^/tools, roles: ROLE_SUPER_ADMIN, requires_channel: http }
        - { path: ^/page, roles: [IS_AUTHENTICATED_ANONYMOUSLY] }
