<?php

namespace ChildConnect\CCSoftBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CodeEnfantRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CodeEnfantRepository extends EntityRepository
{
	public function codeExist($code) {
		$queryBuilder = $this->_em->createQueryBuilder()
			 ->select('COUNT(ce)')
			  ->from($this->_entityName, 'ce')
			  ->where('ce.code LIKE :code')
			  ->setParameter('code',$code)
			  ->getQuery()->getSingleScalarResult();
			  
		return $queryBuilder;
	}
}
