<?php

namespace ChildConnect\CCSoftBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * EnfantQuizRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EnfantQuizRepository extends EntityRepository
{
	public function findQuizsByEnfant($enfant,$newEnfant = false) {
		$queryBuilder = $this->_em->createQueryBuilder()
			 ->select('eq')
			  ->from($this->_entityName, 'eq')
			  ->innerJoin('eq.quiz','qz')
			  ->where('eq.enfant = :enfant')
			  ->setParameter('enfant',$enfant)
			   ->orderBy('eq.id','DESC')
			   ->groupBy('eq.quiz');
		if(!$newEnfant)
			$queryBuilder->andWhere('eq.dateResponded IS NOT NULL');
			  
		$r = $queryBuilder->getQuery()->getResult();
		return  $r;
	}
	public function getQuizs($enfant) {
		$queryBuilder = $this->_em->createQueryBuilder()
		 ->select('eq')
		->from($this->_entityName, 'eq')
		->innerJoin('eq.quiz','qz')
		->where('eq.enfant = :enfant')
		->setParameter('enfant',$enfant)
		->getQuery()->getResult();
		$r= array();
		foreach($queryBuilder as $q)
			$r[$q->getQuiz()->getId()] = $q->getId();
		return $r;
	}
	public function findLatestEnfantQuizByEnfantAndQuiz($enfant,$quiz,$newEnfant = false) {
			   
		$queryBuilder = $this->_em->createQueryBuilder()
			 ->select('eq')
			  ->from($this->_entityName, 'eq')
			   ->where('eq.enfant = :enfant')
			  ->setParameter('enfant',$enfant)
			  ->andWhere('eq.quiz = :quiz')
			   ->setParameter('quiz',$quiz)
			   //->andWhere('eq.dateResponded IS NOT NULL')
			  ->orderBy('eq.dateResponded', 'DESC')
			  ->setMaxResults( 1 )
			  ->getQuery()->getOneOrNullResult();
			 
		return $queryBuilder;
	}
}
