<?php

namespace ChildConnect\CCSoftBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * eventRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EventRepository extends EntityRepository
{

	public function findEntantByAssocation($association) {
		$queryBuilder = $this->_em->createQueryBuilder()
			->select(array('ev','e','a'))
			->from($this->_entityName, 'ev')
			->leftJoin('ev.enfant','e')
			->leftJoin('e.associations', 'a')
			->where('a = :association')
			->setParameter(':association',$association)
			->getQuery()->getResult();
	
		return $queryBuilder;
	}
}
