<?php

namespace ChildConnect\CCSoftBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * QuestionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class QuestionRepository extends EntityRepository
{
	public function getQuestions($quiz,$enfant = null, $enfantQuiz = null) {
            
            $queryBuilder = $this->_em->createQueryBuilder()
			 ->select(array('q','rp','rt','tq'))
			  ->from($this->_entityName, 'q')
			  ->innerJoin('q.quiz','qz')
			  ->innerJoin('q.themeQuestion','tq')
			  ->leftJoin('q.responseProposal','rp')
			  ->leftJoin('q.responseType','rt')
			  ->where('qz = :quiz')
			  ->setParameter('quiz',$quiz->getId())
			  ->OrderBy('tq.ordre','ASC')
			  ->addOrderBy('q.ordre','ASC')
			  ->addOrderBy('rp.ordre','ASC')
			  //->addOrderBy('rp.id','ASC')
			  ->getQuery()->getResult();
			  
		return $queryBuilder;
	}
	
}
