<?php

namespace ChildConnect\CCSoftBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * QuizRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class QuizRepository extends EntityRepository
{
	public function findOrderedQuestions($id) {
            
            $query = $this->_em->createQueryBuilder()
			 ->select(array('qz', 'q','rp','rt','tq'))
			  ->from($this->_entityName, 'qz')
			  ->innerJoin('qz.question','q')
			  ->innerJoin('q.themeQuestion','tq')
			  ->leftJoin('q.responseProposal','rp')
			  ->leftJoin('q.responseType','rt')
			  ->where('qz.id = :id')
			  ->setParameter('id',$id)
			  ->OrderBy('tq.ordre','ASC')
			  ->addOrderBy('q.ordre','ASC')
			  ->addOrderBy('rp.ordre','ASC')
			  //->addOrderBy('rp.id','ASC')
			  ->getQuery();
            
            throw new \Exception(print_r($query->getFirstResult()));
            
		return $query->getFirstResult();
	}
}
