<?php

namespace ChildConnect\CCSoftBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ResponseProposalRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ResponseProposalRepository extends EntityRepository
{
	public function getResponsesProposalByQuiz($quiz) {
		$queryBuilder = $this->_em->createQueryBuilder()
			->select(array('MAX(rp.value) as value'))
			 ->from($this->_entityName, 'rp')
			 ->leftJoin('rp.question','q')
			 ->leftJoin('q.quiz','qz')
			 ->where('qz = :quiz')
			 ->andWhere('q.activeIntegration = 1')
			 ->groupBy('rp.question')
			 //->having('MAX(rp.value)')
			 ->setParameter('quiz',$quiz)
			  ->getQuery()->getResult();
			;
	
		return $queryBuilder;
	}
	public function getByQuestion($question) {
		$queryBuilder = $this->_em->createQueryBuilder()
			->select('rp')
			 ->from($this->_entityName, 'rp','rp.id')
			 ->innerJoin('rp.question','q')
			 ->where('q = :question')
			 ->setParameter('question',$question)
			 ->orderBy('rp.id','ASC')
			   ->getQuery()->getResult();
		return $queryBuilder;
	}
}
