<?php

namespace ChildConnect\CCSoftBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ThemeQuestionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ThemeQuestionRepository extends EntityRepository
{
	public function getThemes($quiz) {
		$queryBuilder = $this->_em->createQueryBuilder()
			 ->select(array('tq'))
			  ->from($this->_entityName, 'tq')
			  ->innerJoin('tq.question','q')
			  ->innerJoin('q.quiz','qz')
			  ->where('qz = :quiz')
			  ->setParameter('quiz',$quiz->getId())
			  ->OrderBy('tq.ordre','ASC')
			  ->addOrderBy('q.ordre','ASC')
			  ->getQuery()->getResult();
			  
		return $queryBuilder;
	}
}
