<?php

namespace ChildConnect\CCSoftBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository
{
	public function findUsers($show=false,$user) {
		$ids_admin = array();
		if($show == 'membre') {
			$query_admin =  $this->_em->createQueryBuilder()
				->select('u.id')
				->from($this->_entityName, 'u')
				->innerJoin('u.groups','g')
				->where('g.id = 4')
				->orWhere('g.id = 3')
				->getQuery()->getScalarResult();
			
			foreach($query_admin as $ele) 
				$ids_admin[] = $ele['id'];
		}
		if($show == 'assoc') {
			$query_admin =  $this->_em->createQueryBuilder()
				->select('u.id')
				->from($this->_entityName, 'u')
				->innerJoin('u.groups','g')
				->where('g.id = 4')
				->getQuery()->getScalarResult();
			foreach($query_admin as $ele) 
				$ids_admin[] = $ele['id'];
		}
		
		$queryBuilder = $this->_em->createQueryBuilder();
		
		$queryBuilder->select('u')
		->from($this->_entityName, 'u')
		->innerJoin('u.groups','g');
	
		if($show =='membre' || $show =='assoc' && count($ids_admin))
			$queryBuilder->leftJoin('u.association','a')->where( $queryBuilder->expr()->notIn('u.id',$ids_admin) );
		
		if($show =='membre' && count($ids_admin)) {
			$queryBuilder
			  ->andWhere('a = :association')
			  ->setParameter('association' , $user->getAssociation());
		}
		
		return $queryBuilder->getQuery()->getResult();
		
	}
}
